import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
export default function Home({users}) {
  const router = useRouter()
  const number = 3
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='title'>Home</h1>
      <style jsx>{`
        .title {
          color: yellow;
          display: ${number > 2 ? 'block' : 'none'};
        }
      `}</style>
      <h1>Homepage</h1>
      <h2>User List</h2>
      {users.map((user)=>(
        <div key={user.id} onClick={()=>router.push(`user/${user.id}`)} style={{cursor:'pointer'}}>
          <h3 style={{color:'green'}}>{user.id}-{user.name}</h3>
        </div>
      ))}
      <Image src='https://images.unsplash.com/photo-1665686310934-8fab52b3821b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxlZGl0b3JpYWwtZmVlZHwxfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60' height={300} width={300}/>
        </div>
)}

export const getStaticProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/users')
  const users = await res.json()
  return {
    props: {
      users
    }
  }
}